version: '3.8'

services:
  frontend:
    container_name: Frontend
    build: ./Frontend
    ports:
      - "8001:8000"
    
  backend:
    container_name: Backend
    build: ./Backend
    ports:
      - "8002:8000"